apiVersion: v1
entries:
  db:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-09-01T15:24:02.1471964Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 43f364c339fa5c958591c4db5740d597848da9c6c07aed3f1fa5e2c592402542
    home: huwelijksplanner.online
    icon: huwelijksplanner.online
    name: db
    urls:
    - db-0.1.0.tgz
    version: 0.1.0
  pan:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-09-01T15:24:02.1513033Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 3793772a602c55ae26c39d9012e9f6bab6a42ca15d9f5be3ca38b4f0d7f6c854
    home: www.zuid-drecht.nl
    icon: www.zuid-drecht.nl
    name: pan
    urls:
    - pan-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-01T15:24:02.142406Z"
