apiVersion: v1
entries:
  pan:
  - apiVersion: v1
    appVersion: V1.0
<<<<<<< Updated upstream
    created: "2020-09-26T09:06:20.7978344Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 7c3ac0f1d7bf12284f2119e48524112be8ad027489476c3b7862b3398a09233b
=======
    created: "2020-09-25T12:21:04.183541742Z"
    description: '&quot;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&quot;'
    digest: 71df3487e16df1f55e1ac8613fb7b7a4c759bac5b92d5124a3d62e53260cf920
>>>>>>> Stashed changes
    home: www.zuid-drecht.nl
    icon: www.zuid-drecht.nl
    name: pan
    urls:
    - pan-0.1.0.tgz
    version: 0.1.0
<<<<<<< Updated upstream
generated: "2020-09-26T09:06:20.7908415Z"
=======
generated: "2020-09-25T12:21:04.165614543Z"
>>>>>>> Stashed changes
