apiVersion: v1
entries:
  pan:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-06T07:09:59.935156698Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: f9d47d3d0eb7fee8565cbfe3df48a8dcd330c23027df49c6eaf15f22e42e92d5
    home: www.zuid-drecht.nl
    icon: www.zuid-drecht.nl
    name: pan
    urls:
    - pan-0.1.0.tgz
    version: 0.1.0
  pc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-06T07:10:00.106736993Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 0b241991c441ce65541b5bc63bebefe1242253a97b5fa8fbdc1894437ed12591
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-06T07:09:59.8555614Z"
