apiVersion: v1
entries:
  pan:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-08-10T05:54:33.5888711Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 5a93a520ee18e21a9d54d7f860e9ac88d1ed26d180f704fe7d703320ce8b4920
    home: www.zuid-drecht.nl
    icon: www.zuid-drecht.nl
    name: pan
    urls:
    - pan-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-10T05:54:33.5824547Z"
