apiVersion: v1
entries:
  pan:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-10-07T05:14:17.7338552Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 0b69855ae9eb82592b454f8f7fb2eeb59b741655085b5ae41ce4b9ebaddb5acb
    home: www.zuid-drecht.nl
    icon: www.zuid-drecht.nl
    name: pan
    urls:
    - pan-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-07T05:14:17.7292736Z"
