apiVersion: v1
entries:
  pan:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-05-29T10:22:18.63867367Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 4429a064f7edb13414005680a909dfe48b5d4ed11553f85da9ecff90aa9c11bc
    home: pan.conduction.nl
    icon: pan.conduction.nl
    name: pan
    urls:
    - pan-0.1.0.tgz
    version: 0.1.0
generated: "2020-05-29T10:22:18.63548537Z"
