apiVersion: v1
entries:
  pan:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-08-18T09:53:56.3586686Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 2a0cc7771cb39ff77c41297100b7cbce274d73a0cfda44d9f13872182d5e2f5e
    home: www.westfriesland.commonground.nu
    icon: www.westfriesland.commonground.nu
    name: pan
    urls:
    - pan-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-18T09:53:56.3521191Z"
