apiVersion: v1
entries:
  pan:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-10-21T11:50:14.501641496Z"
    description: '&quot;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&quot;'
    digest: e175bceec34345c63a89d2a4a4684be04acc4cb83859786ba77b532e97f7701e
    home: www.westfriesland.commonground.nu
    icon: www.westfriesland.commonground.nu
    name: pan
    urls:
    - pan-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-21T11:50:14.495206096Z"
