apiVersion: v1
entries:
  pan:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-08-19T11:33:55.586836275Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: e1250cbc3063735d06b28a10adf42350e0cd03321455b2586d44dc38d252ef21
    home: www.westfriesland.commonground.nu
    icon: www.westfriesland.commonground.nu
    name: pan
    urls:
    - pan-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-19T11:33:55.584077675Z"
