# An empty secret (with no data) in order for the update to work
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-letsencrypt-certs
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque