apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}-letsencrypt
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: {{ include "name" . }}-letsencrypt
  ports:
  - protocol: "TCP"
    port: 80